language: node_js
node_js:
- '10'
branchs:
  only:
  - master
script:
  - yarn build
before_install:
  - ls -al ~
  - touch ~/.ssh/id_rsa
  - openssl aes-256-cbc -K $encrypted_504d3c551bdc_key -iv $encrypted_504d3c551bdc_iv -in id_rsa.enc -out ~\/.ssh/id_rsa -d
after_success:
  - ssh travis@47.96.70.2 -o StrictHostKeyChecking=no